server:
  port: 8085

spring:
  application:
    name: CITY-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/city-service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  sql:
    init:
      encoding: UTF-8
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
debug: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/