services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: measurements
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customers
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
  mysql:
    driver: bridge
volumes:
  postgres:
  mysql: