services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: measurement-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user-service
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - mongodb
networks:
  postgres:
    driver: bridge
  mysql:
    driver: bridge
  mongodb:
    driver: bridge
volumes:
  postgres:
  mysql:
  mongodb: