spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

server:
  port: 8089

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true


#resilience4j:
#  circuitbreaker:
#    instances:
#      myCircuitBreaker:
#        register-health-indicator: true
#        event-consumer-buffer-size: 10
#        automatic-transition-from-open-to-half-open-enabled: true
#        failure-rate-threshold: 50
#        minimum-number-of-calls: 5
#        permitted-number-of-calls-in-half-open-state: 3
#        sliding-window-size: 10
#        wait-duration-in-open-state: 55s
#        sliding-window-type: COUNT_BASED