spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

server:
  port: 8089

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true


resilience4j:
  circuitbreaker:
    instances:
      cityCircuitBreaker:
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 10000  # 10 seconds in milliseconds
        failure-rate-threshold: 50
      measurementCircuitBreaker:
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 50
        slow-call-duration-threshold: 100000
      notificationCircuitBreaker:
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 50
      userCircuitBreaker:
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 50
