spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: city
          uri: ${CITY_ROUTE_URI:http://localhost:8085}
          predicates:
            - Path=/api/v1/cities/**
        - id: measurement
          uri: ${MEASUREMENT_ROUTE_URI:http://localhost:8086}
          predicates:
            - Path=/api/v1/measurements/**
        - id: notification
          uri: ${NOTIFICATION_ROUTE_URI:http://localhost:8087}
          predicates:
            - Path=/api/v1/notifications/**
        - id: user
          uri: ${USER_ROUTE_URI:http://localhost:8088}
          predicates:
            - Path=/api/v1/users/**

server:
  port: 8089

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


