server:
  port: 8086

spring:
  application:
    name: measurement
  datasource:
    url: jdbc:postgresql://localhost:5433/measurement-service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  sql:
    init:
      encoding: UTF-8
