server:
  port: 8086

spring:
  application:
    name: measurement-service
  datasource:
    url: jdbc:postgresql://localhost:5433/measurement-service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  sql:
    init:
      encoding: UTF-8
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
debug: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

clients:
  city:
    url: http://localhost:8085