spring:
  application:
    name: NOTIFICATION-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification-service

server:
  port: 8087


eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
